### ISSUE TITLE
Some of the module versions on hack.nest.land have two v's

### ISSUE THREAD

**Issue by mjrlowe** [nestdotland/hacktoberfest-2020#30]
Not sure what is causing this. (Perhaps the newer `egg` version stores versions with a `v` and previous versions didn't?)

**Comment by maximousblk** [comment]
https://github.com/nestdotland/hacktoberfest-2020/blob/52ab2e699031926c743e02cc401e4debac6c2d42/src/views/Submissions.vue#L31
seems like an easy fix
